apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/docker-compose.yaml -o /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/Deploy
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: eshoppublicapi
  name: eshoppublicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshoppublicapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/docker-compose.yaml -o /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/Deploy
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/task3-default: "true"
        io.kompose.service: eshoppublicapi
    spec:
      containers:
        - image: eshoppublicapi
          name: eshoppublicapi
          resources: {}
      restartPolicy: Always
status: {}
