apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/docker-compose.yaml -o /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/Deploy
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/docker-compose.yaml -o /mnt/c/Users/SGreyling/Desktop/Technical/Technical Test/Task3/Deploy
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/task3-default: "true"
        io.kompose.service: sqlserver
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: '@someThingComplicated1234'
          image: mcr.microsoft.com/azure-sql-edge
          name: sqlserver
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
